### ISSUE TITLE
vite 3 support

### ISSUE THREAD

**Issue by reslear** [Shinigami92/vite-plugin-time-reporter#19]

**Comment by reslear** [comment]
<img width="616" alt="Screenshot 2022-10-06 at 13 03 54" src="https://user-images.githubusercontent.com/12596485/194297226-a3afe844-dbdc-455e-9e6d-73accc5b6230.png">

**Comment by reslear** [comment]
<img width="484" alt="Screenshot 2022-10-06 at 13 21 32" src="https://user-images.githubusercontent.com/12596485/194300347-eb52ab96-5617-47c8-8a54-4139218b9d50.png">

**Comment by Shinigami92** [comment]
Maybe you need to use `import * as timeReporter from 'vite-plugin-time-reporter';` or something like that
Also try to log it with `console.log(timeReporter)` and `console.log(typeof timeReporter)`

**Comment by reslear** [comment]
try, working

```ts
// @ts-ignore
timeReporter.default(),
```

**Comment by reslear** [comment]
but need in future refactor code :)

**Comment by Shinigami92** [comment]
Or use https://www.typescriptlang.org/tsconfig#esModuleInterop

**Comment by reslear** [comment]
but used `esModuleInterop: true` so other plugins is work fine :)

**Comment by Shinigami92** [comment]
Then I don't know :shrug:
Feel free to have a look at the source
