### ISSUE TITLE
Bug: The engine "pnpm" appears to be invalid

### ISSUE THREAD

**Issue by sshyam-gupta** [Shinigami92/vite-plugin-time-reporter#41]
## Info

| Tool                      | Version                 |
| ------------------------- | ----------------------- |
| vite-plugin-time-reporter | v2.2.0                  |
| Vite                      | v4.3.0                  |
| Node                      | v16.18.0                  |
| OS                        | win,linux,mac           |

## Context
I am using the yarn package manager and while installing the dependencies I see this warning

```
remote:        yarn install v1.22.21
remote:        [1/5] Validating package.json...
remote:        [2/5] Resolving packages...
remote:        [3/5] Fetching packages...
remote:        warning vite-plugin-time-reporter@2.2.0: The engine "pnpm" appears to be invalid.
remote:        [4/5] Linking dependencies...
remote:        [5/5] Building fresh packages...
remote:        Done in 55.97s.
```

I saw a similar report on yarn https://github.com/yarnpkg/yarn/issues/7560, is there any way to supress this warning?

**Comment by Shinigami92** [comment]
It's a warning
Just ignore it, or search yarn's docs
