### ISSUE TITLE
Bug: No Vite v5 support

### ISSUE THREAD

**Issue by poshiemaaat** [Shinigami92/vite-plugin-time-reporter#42]
## Info

| Tool                      | Version                 |
| ------------------------- | ----------------------- |
| vite-plugin-time-reporter | v2.2.0                  |
| Vite                      | v5.0.0                  |

## Context
In order to upgrade to vite 5, I either need to wait or uninstall this plugin temporarily until there's support since the peerDependency does not include ^5.0.0

**Comment by Shinigami92** [comment]
will set this on my todo list for tomorrow :+1:

**Comment by poshiemaaat** [comment]
@Shinigami92  😮 that was a quick response! Love it. Thank you so much!

**Comment by Shinigami92** [comment]
support added via [82eda48](https://github.com/Shinigami92/vite-plugin-time-reporter/commit/82eda48860494cc2b58c7dd8ddab8d8b1cabe08b)
